### ISSUE TITLE
Why can't I use docker.sunet.se/openjdk-jre-luna:luna7.4-jre11?

### ISSUE THREAD

**Issue by celikfatih** [SUNET/docker-openjdk-luna#1]
I was using `docker.sunet.se/openjdk-jre-luna:luna7.4-jre11` before. But I deleted the image on my machine and then when I try to download it again, I keep getting an error like this? I don't fully understand why? Can you help?

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

**Comment by leifj** [comment]
Hi - we don't guarantee the binary builds but the reason you can't find them is that they were recently renamed to deal with the deprecation of the openjdk base image. Look in the Makefile to find the new naming.

**Comment by celikfatih** [comment]
Thanks for the answer, I wasn't aware that the nomenclature had changed. I checked your changes in the Makefile and made it suitable. The problem is fixed.
